### ISSUE TITLE
Találtam egy még rövidebbet ide :)

### ISSUE THREAD

**Issue by ricsiadobos** [SmartHomeEcho/balkezesek#1]
adatok.Where(x=>x.Utolso.ToString("yyyy-MM").Contains("1999-10")).ToList().ForEach(x => Console.WriteLine($"\t{x.Nev} {Math.Round(x.Magassag * 2.54, 1)} cm"));

**Comment by SmartHomeEcho** [comment]
Ez jobb , köszi:)
